services:
  social:
    build:
      context: .
    container_name: social-web
    ports:
      - "3005:80"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx-web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - social
    restart: always
